#hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: zclau
subtitle: Keep it simple,stupid  
description: Keep it simple,stupid
author: zclau
language: zh-Hans
timezone:
email: cleverutd@gmail.com

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://zclau.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
  backtick_code_block: true

# Category & Tag
default_category: uncategorized
category_map:
     Web开发: webdev
     数据库: database
     系统架构: architecture
     网络安全: netsecurity
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
#per_page: 5
#pagination_dir: page

index_generator:
    per_page: 5
archive_generator:
    per_page: 20
tag_generator:
    per_page: 20


# Archives 默认值为2，这里都修改为1，相应页面就只会列出标题，而非全文
# ## 2: Enable pagination
# ## 1: Disable pagination
# ## 0: Fully Disable
archive: 1
category: 1
tag: 1

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
plugins:
    - hexo-generator-sitemap

theme: next

#deployment
## Docs: http://hexo.io/docs/deployment.html
deploy: 
  - type: git
    repo: git@github.com:cleverUtd/cleverUtd.github.io.git
    branch: master
 # - type: rsync
 #   host: zclau.com 
 #   user: zclau
 #   root: /home/zclau/blog

#duoshuo
duoshuo_shortname: zclau

#baidu analytics
baidu_analytics: 67a0f42b403ccee34010e0409124f3d7 #345dc5e728ac6d5542c0144d4223d437

# hexo sitemap网站地图
sitemap:
    path: sitemap.xml

# swiftype search engine
#swiftype_key: WGvTssMEM7NA3E1tbRdY

# rss feed
feed: 
    type: atom
    path: atom.xml
    limit: 10
