menu:
  首页: /
  归档: /archives
  
  #about: /about

submenu:
  订阅: /atom.xml

widgets:
# - recent_posts
#- search
- category
- archive
# - tag
- tagcloud
- weibo

excerpt_link: Read More
comment_link: Comments

# header头像
avatar: /avatar.png

baidu_share: true

# 请到baidu_tongji.ejs中替换代码
baidu_tongji: true

fancybox: true

rss: /atom.xml

# enable是否开启；height小挂件高度；url替换成自己的微博挂件地址，同步修改url中height的值
weibo:
  enable: true
  height: 800
  url: http://widget.weibo.com/weiboshow/index.php?language=&width=0&height=800&fansRow=1&ptype=1&speed=0&skin=1&isTitle=1&noborder=1&isWeibo=1&isFans=0&uid=1725565983&verifier=eb14beec&dpc=1

# 评论提供可以选择 duoshuo 或者 wumii，无需评论，此处不填就行。
comment_provider: duoshuo

duoshuo:
  short_name: zclau